readme_table_content
esgaelramos/MyMoneyUP pull request #129
Opened 2024-01-17 01:17 UTC by memonsalvo

2024-01-17 16:49 UTC, esgaelramos requested changes
Are you sure that is visible into the README?
please:
+ change the description of image for any like: 'Flow of Website...'
+ try to compress the gif, 20M its a lot
+ check if the urls of contents are correct (in work and syntax)

thanksss:)

2024-01-17 20:24 UTC, memonsalvo commented
correcciones realizadas

2024-01-17 20:45 UTC, esgaelramos commented
are you sure?

2024-01-17 22:05 UTC, memonsalvo commented
Confirmed, the gif was compressed by 6% and the links were verified.

2024-01-26 18:28 UTC, CamilaPua commented on .github/fordevs/imgs/Flow_of_Website.gif
i get a "Unable to render rich display" will be that a problem after the merge?

2024-01-26 23:02 UTC, memonsalvo commented on .github/fordevs/imgs/Flow_of_Website.gif
I don't really know, woman, I owe it to you

2024-01-27 16:05 UTC, esgaelramos commented
Re-Write please, in a branch

2024-01-27 16:05 UTC, closed without merging