Cambios en Views para implementar API CALL
esgaelramos/MyMoneyUP pull request #63
Opened 2023-12-12 18:59 UTC by LorenzoFerreyra

2023-12-12 19:45 UTC, esgaelramos commented on requirements-dev.txt
> +pandas
si agregamos nuevas libs y serán usadas en prod, hay que agregar las librerías en ambos archivos requirements:)

2023-12-12 19:48 UTC, esgaelramos commented on moneytracker/views.py
> +                    email_body += f'Ticker: {ticker}, Precio: {data["price"]}\n'
está genial, pero en estos casos por fa puedes agregar una captura de cómo se ve el cambio:)

2023-12-12 20:06 UTC, esgaelramos commented on moneytracker/views.py
>          }
uff, está excelente poder obtener desde ahí la lista de activos, mi duda y tema que debemos checar con @CamilaPua, es la manera más óptima pues:
+ cuál es el objetivo de tener nosotros una entidad Asset si se obtendrá de la API directa?
+ será nuestra única fuente 'oficial'?

se aceptan propuestas: según lo decidido deberíamos 
+ qué alternativa para mantener sincronizados los valores tenemos? a partir de la api y checarlo

2023-12-14 00:34 UTC, CamilaPua requested changes

2023-12-14 00:34 UTC, CamilaPua commented on moneytracker/views.py
> +        # Accedemos a la COINBASE API para obtener la lista de activos disponibles
in english please jajja

2023-12-14 00:34 UTC, CamilaPua commented on templates/moneytracker/tracker.html
> +        <form action="/" method="post" class="main-form">
por qué cambiaste esto?

2023-12-14 00:34 UTC, CamilaPua commented on moneytracker/views.py
> +        selected_assets_tickers = request.POST.getlist('assets')
nos explicas porfi por qué es tickers? (solo quiero entender, soy junior ajjaja)

2023-12-26 21:14 UTC, esgaelramos commented
I need to close this PR:)
The # of conflicts is too long, haha, soo, please develop if is necessaty this feature in a new branch (dont forget update main) thankss:)  
But probably all this code was implemented in this others: https://github.com/esgaelramos/MyMoneyUP/commit/adbc6d59036711bf767ca72cec62abf992dc75d4 and https://github.com/esgaelramos/MyMoneyUP/commit/1629be03219ca9bbd35219a78779b105d6a6bf45

2023-12-26 21:14 UTC, closed without merging