Welcome Message for Users
esgaelramos/MyMoneyUP pull request #72
Opened 2023-12-20 15:30 UTC by LorenzoFerreyra

Added a welcome message for users including cripto price and asset symbols

2023-12-20 15:37 UTC, LorenzoFerreyra commented
For next step, we're missing:
*Another message telling users their subscribed assets performance, which could be based on an HTML template with some design.
* This will be sent based on certain fixed period (a number of days chosen by the users).
* We still need a feature that lets users choose this period

2023-12-21 19:26 UTC, esgaelramos requested changes
Great change, small and directly...
My recommendation:
+ Refac for integrate new changes
+ Encapsular this logic in a function???
+ For the tests we need Mock the LiveCrypto and his return (get_value?) and the pd method iloc, haha, it's alot, for that it's better create a new function

2023-12-21 19:26 UTC, esgaelramos commented on moneytracker/views.py
> +                except RequestException as e:
Check if we don't use a except for ValueError?

2023-12-21 22:18 UTC, LorenzoFerreyra commented
Cami also thinks it's a good idea to make all this a unique function and call it appropriately 👍🏼 
We can discuss it now when we meet

2023-12-26 21:10 UTC, esgaelramos commented
I need to close this PR:)
The # of conflicts is too long, haha, soo, please develop if is necessaty this feature in a new branch (dont forget update main) thankss:)

2023-12-26 21:10 UTC, closed without merging